# Generated by Django 4.2.1 on 2023-07-29 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('renter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=130)),
                ('rent_price', models.FloatField(blank=True, default=0)),
                ('address', models.CharField(max_length=150)),
                ('current_tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='renter.renter')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locaux',
            },
        ),
    ]
