# Generated by Django 4.2.1 on 2023-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_local_rented_since_alter_local_current_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
