# Generated by Django 4.2.1 on 2023-10-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_local_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='rent_price',
            field=models.FloatField(blank=True),
        ),
    ]
