# Generated by Django 4.2.1 on 2023-07-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0004_alter_payment_options_renter_tenant_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
