# Generated by Django 4.2.1 on 2023-07-30 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
        ('renter', '0005_renter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='local.local'),
        ),
    ]
