# Generated by Django 4.2.1 on 2023-08-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0006_payment_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='payment_date',
        ),
    ]
