# Generated by Django 4.2.1 on 2023-08-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0007_remove_renter_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renter',
            old_name='tenant_since',
            new_name='added_at',
        ),
    ]
