# Generated by Django 4.2.1 on 2023-08-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0008_rename_tenant_since_renter_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
