# Generated by Django 4.2.1 on 2023-08-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0009_alter_renter_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
