# Generated by Django 4.2.1 on 2023-08-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0010_alter_payment_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='address',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='renter',
            name='phone',
            field=models.CharField(max_length=130, null=True, unique=True),
        ),
    ]
