# Generated by Django 4.2.1 on 2023-10-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0011_alter_renter_address_alter_renter_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renter',
            options={'ordering': ['-added_at'], 'verbose_name': 'Locataire', 'verbose_name_plural': 'Locataires'},
        ),
    ]
