# Generated by Django 4.2.1 on 2023-11-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0012_alter_renter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='address',
            field=models.CharField(max_length=130, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='first_name',
            field=models.CharField(max_length=130, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='last_name',
            field=models.CharField(max_length=13, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='phone',
            field=models.CharField(max_length=130, null=True, unique=True, verbose_name='Téléphone'),
        ),
    ]
