# Generated by Django 4.2.1 on 2023-11-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_alter_local_rent_price'),
        ('renter', '0013_alter_renter_added_at_alter_renter_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rent', 'Rent a local'), ('unrent', 'Unrent a local'), ('payment', 'Payment of rent')], max_length=20)),
                ('act_at', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.local')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renter.renter')),
            ],
        ),
    ]
