# Generated by Django 4.2.1 on 2023-11-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0014_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
